baseURL = 'https://git.fbcf.xyz/'
languageCode = 'en-us'
title = 'Felix B'
theme = 'archie-efbicief'
copyright = "© Felix B"
# Code Highlight
pygmentsstyle = "monokai" #gruvbox-dark?
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=100 # articles per page

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Computer Systems Engineering (MEng) student at the University of Warwick."
  bio = "Hi! My name is Felix, I'm an undergraduate masters student at the University of Warwick, studying Computer Systems Engineering. I have experience with Haskell, Python, C, JavaScript/React, Java, and Bash. I am also Tech Officer for Warwick Minecraft Society and Warwick Computing Society."

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/efbicief"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Projects"
url = "/tags/project"
weight = 2

[[menu.main]]
name = "Blog Posts"
url = "/tags/blog"
weight = 3

[[menu.main]]
name = "Notes"
url = "/tags/notes"
weight = 3

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 4

[[menu.main]]
name = "All Tags"
url = "/tags"
weight = 5